ArbiShop/ArbiShop/urls.py
"""
file:urls.py
    This module defines the url patterns for the djangoTimeProject application.
    URL configuration for ArbiShop project.
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('users/', include('users.urls')),
                  path('', include('products.urls')),
                  path('password-reset-complete/',
                       auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
                       name='password_reset_complete'),
                  path('seller/', include('seller.urls')),
                path('chat/', include('chat.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ArbiShop/chat/urls.py
"""
URL routing for the chat application.

This module defines the URL patterns for the chat application, mapping URLs to views that handle
chat room interactions, including creating or retrieving chat rooms and accessing specific chat rooms.
"""

from django.urls import path
import chat.views as chat_views

urlpatterns = [
    path('<int:room_id>/', chat_views.ChatRoomView.as_view(), name='chat_room'),
    path('start/<int:seller_id>/', chat_views.CreateOrGetChatRoomView.as_view(), name='create_or_get_chat_room'),
]

ArbiShop/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from users.views import SignUpView, LoginView, LogoutView, ResetPasswordView, ProfileUpdateView, UserProfileView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='user-profile'),
    path('profile-update/', ProfileUpdateView.as_view(), name='update_profile'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
]

ArbiShop/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static "style.css" %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

    <style>
        .chat-container {
            max-width: 100%;
            margin: 0 auto;
            padding: 10px;
        }

        .chat-header {
            text-align: center;
            background-color: #075e54;
            color: #fff;
            padding: 10px;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }

        .chat-header h1 {
            font-size: 24px;
        }

        .chat-logout {
            text-align: right;
            padding: 10px;
        }

        .chat-logout a {
            text-decoration: none;
            color: #075e54;
            font-weight: bold;
        }

        .chat-logout a:hover {
            text-decoration: underline;
        }

        .chat__item__container {
            background-color: #f5f5f5;
            padding: 10px;
            border-radius: 10px;
            height: 300px;
            max-height: 300px;
            overflow-y: auto;
        }

        .chat-input-container {
            display: flex;
            align-items: center;
        }

        #id_message_send_input {
            flex: 1;
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }

        #id_message_send_button {
            padding: 5px 10px;
            background-color: #075e54;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            margin-left: 10px;
        }

        .chat-message {
            background-color: #e4f9f5;
            border-radius: 10px;
            margin: 10px 0;
            padding: 10px;
            position: relative;
        }

        .chat-message.right {
            background-color: black;
            width: 80%;
            float: right;
            clear: both;
            margin-left: auto;
            margin-right: 0;
        }

        .chat-message.left {
            background-color: #075e54;
            width: 80%;
            float: left;
            clear: both;
            margin-left: 0;
            margin-right: auto;
        }

        .chat-message span {
            font-weight: bold;
            color: white;
        }

        .message-timestamp {
            font-size: 10px;
            position: absolute;
            top: 5px;
            right: 5px;
        }

        .message-username {
            font-size: 12px;
            position: absolute;
            bottom: 5px;
            right: 5px;
        }
    </style>



    <title>{% block title %} {% endblock %} </title>
    {% block extra_head %} {% endblock %}
</head>
<body>
  <div class="container p-3 my-3">
    <div class="row">
      <div class="col-md-12">
        {% include "navbar.html" %}
        {% if messages %}
          <div class="alert alert-dismissible" role="alert">
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
  <script src="{% static 'javascipt/cart.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>
    {% block extra_scripts %}  {% endblock %}
</body>
</html>

ArbiShop/templates/category_listing.html
{% load widget_tweaks %}

{% block content %}

<div class="container mt-4">
    <div class="row">
    <div class="col-md-3 col-sm-6 mb-4">
    <div class="dropdown">
        <a class="btn btn-primary dropdown-toggle w-100 py-3 h-100" href="#" id="categoryDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
        </a>
        <div class="dropdown-menu w-500 p-3" aria-labelledby="categoryDropdown" style="columns: 2; -webkit-columns: 2; -moz-columns: 2;">
            {% for category in categories|slice:"4:" %}
            <a class="dropdown-item py-2" href="{% url 'category-products' category.id %}">{{ category.name }}</a>
            {% endfor %}
        </div>
    </div>
</div>
        {% for category in categories|slice:":4" %}
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="{% url 'category-products' category.id %}" class="text-decoration-none">
                <div class="card text-center h-100 bg-black">
                    <div class="card-body">
                        <h5 class="card-title text-white">{{ category.name }}</h5>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}

    

    </div>
</div>

{% endblock %}

<style>

    .dropdown-menu {
        background-color: #ffffff;
        border-radius: 4px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .dropdown-item {
        color: #007bff;
        font-weight: 500;
        padding: 8px 16px;
        white-space: nowrap;
        display: block;
    }

    .dropdown-item:hover {
        background-color: #f0f0f0;
        color: #0056b3;
    }

    .dropdown-toggle {
        text-align: center;
        padding: 10px 0;
    }

    .dropdown-menu[style*="columns: 2"] {
        column-gap: 1rem;
    }

    .dropdown-item {
        margin-bottom: 8px;
    }


    .card-title {
        font-size: 1.2rem;
    }

    .card {
        border: none;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        transition: all 0.3s ease-in-out;
    }

    .card:hover {
        transform: translateY(-5px);
    }
</style>

ArbiShop/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-light shadow-sm" style="background-color: #f0f5f5;">
    <div class="container">
        <a href="/" class="navbar-brand">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'users:user-profile' %}" class="nav-link">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:logout' %}" class="nav-link">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'users:login' %}" class="nav-link">Sign in</a>
                    </li>
                {% endif %}
                <li class="nav-item position-relative">
                    <a href="{% url 'cart' %}" class="nav-link">
                        <i class="fas fa-shopping-cart"></i>
                        <span id="cart-count" class="badge badge-pill badge-danger position-absolute" style="top: -5px; right: -5px;">0</span>
                    </a>
                </li>
                <li class="nav-item position-relative">
                    <a href="#" class="nav-link">
                        <i class="fas fa-bell"></i>
                        <span id="notification-count" class="badge badge-pill badge-danger position-absolute" style="top: -5px; right: -5px;">3</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>