ArbiShop/ArbiShop/urls.py
"""
file:urls.py
    This module defines the url patterns for the djangoTimeProject application.
    URL configuration for ArbiShop project.
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('users/', include('users.urls')),
                  path('', include('products.urls')),
                  path('password-reset-complete/',
                       auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
                       name='password_reset_complete'),
                  path('seller/', include('seller.urls')),
                path('chat/', include('chat.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ArbiShop/chat/urls.py
"""
URL routing for the chat application.

This module defines the URL patterns for the chat application, mapping URLs to views that handle
chat room interactions, including creating or retrieving chat rooms and accessing specific chat rooms.
"""

from django.urls import path
import chat.views as chat_views

urlpatterns = [
    path('<int:room_id>/', chat_views.ChatRoomView.as_view(), name='chat_room'),
    path('start/<int:seller_id>/', chat_views.CreateOrGetChatRoomView.as_view(), name='create_or_get_chat_room'),
]

ArbiShop/orders/urls.py
"""
urls.py

Defines URL patterns for the Orders app, mapping views to routes for checkout,
payment processing, and order success.
"""

from django.urls import path
from django.views.generic import TemplateView

from orders.views import CheckoutView, PaymentView, OrderDetailView

app_name = 'orders'
urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('process-payment/', PaymentView.as_view(), name='process_payment'),
    path('order-success/', TemplateView.as_view(template_name='orders/order_success.html'), name='order_success'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order_detail')
]

ArbiShop/seller/urls.py
"""
urls.py

Defines URL patterns for the seller app, including routes for the seller dashboard,
product management, and order items.
"""

from django.urls import path

from seller.views import (
    AddProductView,
    UpdateProductView,
    DeleteProductView,
    SellerDashboardView,
    SellerOrderItemsView,
    SellerChatRoomView,
    SellerChatsView
)

app_name = 'seller'

urlpatterns = [
    path('chat/seller/room/<int:room_id>/', SellerChatRoomView.as_view(), name='seller_chat_room'),
    path("chats", SellerChatsView.as_view(), name="chats"),
    path('dashboard/', SellerDashboardView.as_view(), name='dashboard'),
    path('dashboard/orders', SellerOrderItemsView.as_view(), name='orders'),
    path('dashboard/products', SellerDashboardView.as_view(), name='products'),
    path('dashboard/add-product/', AddProductView.as_view(), name='add_product'),
    path('dashboard/update-product/<int:pk>/', UpdateProductView.as_view(), name='update_product'),
    path('dashboard/delete-product/<int:pk>/', DeleteProductView.as_view(), name='delete_product'),

]

ArbiShop/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from users.views import SignUpView, LoginView, LogoutView, ResetPasswordView, ProfileUpdateView, UserProfileView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='user-profile'),
    path('profile-update/', ProfileUpdateView.as_view(), name='update_profile'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
]

ArbiShop/users/models.py
"""users/models.py
This file is responsible for declaring user model
"""
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from users.managers import CustomUserManager


class Role(models.TextChoices):
    """
    Enum for user roles.
    """
    GENERAL_USER = 'GENERAL_USER', _('General User')
    ADMIN = 'ADMIN', _('Admin')


class CustomUser(AbstractBaseUser, PermissionsMixin):
    """
    Custom user model with email, first name, last name, role, and timestamps.
    """
    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(_("first name"), max_length=30)
    last_name = models.CharField(_("last name"), max_length=30)
    is_staff = models.BooleanField(default=False)
    role = models.CharField(
        _("role"),
        max_length=20,
        choices=Role.choices,
        default=Role.GENERAL_USER
    )
    avatar = models.ImageField(default="default.jpg", upload_to="profile_images/")
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    bio = models.TextField(default="", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = CustomUserManager()

    def __str__(self):
        """
        Return the string representation of the user, which is the email address.

        :return: User's email address
        :rtype: str
        """
        return self.email

ArbiShop/users/forms.py
"""user/forms.py
This file is for declaring Form for User models
"""

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    """
    A class that inherits from UserCreationForm. responsible for creating user form
    """
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name',
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name',
                                                              'class': 'form-control',
                                                              }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']


class CustomUserChangeForm(UserChangeForm):
    """
    A class that inherits from UserChangeForm. responsible for changing the user form
    """

    class Meta:
        model = User
        fields = "__all__"
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter first name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter last name'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter password'}),
            'is_superuser': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'is_staff': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'role': forms.Select(attrs={'class': 'form-control'}),
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'bio': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Bio'}),
            'user_permissions': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }


class LoginForm(forms.Form):
    """
    A class that inherits from UserCreationForm. responsible for creating user form
    """
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter email'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter password'}))


class UserUpdateForm(forms.ModelForm):
    """
    Form for users to update their profile information.
    """

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'avatar', 'bio']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Bio'}),
        }


class UserProfileForm(UserChangeForm):
    """
    Form for users to view their profile information.
    """
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'avatar']

ArbiShop/users/views.py
"""
This module handles user authentication views including signup, login, and logout
using Django's authentication system. It also includes a home view that is
protected by login requirements.

Classes:
    SignUpView: Handles user registration.
    LoginView: Handles user login.
    HomeView: Displays the home page to logged-in users.
    LogoutView: Handles user logout.
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.contrib import messages
from django.views.generic import UpdateView, TemplateView

from orders.models import Order
from users.forms import CustomUserCreationForm, LoginForm, UserUpdateForm
from users.utils import create_jwt_token

from users.constants import PASSWORD_RESET_SUCCESS_MESSAGE, LOGIN_SUCCESS_MESSAGE

User = get_user_model()


class UserProfileView(LoginRequiredMixin, TemplateView):
    """
    Displays the user's profile and order history.

    Renders the user's profile page with personal details and a list of their orders.
    """

    template_name = 'users/user_profile.html'

    def get_context_data(self, **kwargs):
        """
        Adds the user and their orders to the context.
        """
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['user'] = user
        context['orders'] = Order.objects.filter(user=user)
        return context


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    """
    Handles user profile updates.
    """
    model = User
    form_class = UserUpdateForm
    template_name = 'users/update_profile.html'
    success_url = reverse_lazy('users:user-profile')

    def get_object(self):
        """
        Return the current user object.

        :return: User object
        :rtype: User
        """
        return self.request.user

    def form_valid(self, form):
        """
        Process the profile update form and save the user.

        :param form: Validated form
        :type form: UserUpdateForm
        :return: Redirects to profile page or re-renders profile page with success message
        :rtype: HttpResponse
        """
        messages.success(self.request, 'Profile updated successfully')
        return super().form_valid(form)


class SignUpView(View):
    """
    Handles user registration.
    GET request renders the signup form.
    POST request processes the signup form and creates a new user.
    """

    def get(self, request):
        """
        Render the signup form.

        :param request: HTTP GET request
        :type request: HttpRequest
        :return: Rendered signup form
        :rtype: HttpResponse
        """
        form = CustomUserCreationForm()
        return render(request, 'users/signup.html', {'form': form})

    def post(self, request):
        """
        Process the signup form and create a new user.

        :param request: HTTP POST request
        :type request: HttpRequest
        :return: Redirects to home page or re-renders signup form with errors
        :rtype: HttpResponse
        """
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            token = create_jwt_token(user)
            response = redirect('product-list')
            response.set_cookie('jwt', token)
            return response
        return render(request, 'users/signup.html', {'form': form})


class LoginView(View):
    """
    Handles user login.
    GET request renders the login form.
    POST request processes the login form and authenticates the user.
    """

    def get(self, request):
        """
        Render the login form.

        :param request: HTTP GET request
        :type request: HttpRequest
        :return: Rendered login form
        :rtype: HttpResponse
        """
        form = LoginForm()
        next_url = request.GET.get('next', '')
        return render(request, 'users/login.html', {'form': form, 'next': next_url})

    def post(self, request):
        """
        Process the login form and authenticate the user.

        :param request: HTTP POST request
        :type request: HttpRequest
        :return: Redirects to next URL or home page, or re-renders login form with errors
        :rtype: HttpResponse
        """
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            try:
                user = User.objects.get(email=email)
                user = authenticate(request, username=user, password=password)
                if user:
                    login(request, user)  # Log the user in
                    token = create_jwt_token(user)
                    next_url = request.POST.get('next', 'product-list')
                    response = redirect(next_url)
                    response.set_cookie('jwt', token)
                    messages.success(request, LOGIN_SUCCESS_MESSAGE)
                    return response
                else:
                    return HttpResponse('Invalid credentials', status=401)
            except User.DoesNotExist:
                return HttpResponse('Invalid credentials', status=401)
        next_url = request.POST.get('next', '')
        return render(request, 'users/login.html', {'form': form, 'next': next_url})


class LogoutView(View):
    """
    Handles user logout.
    GET request logs out the user and redirects to the login page.
    """

    def get(self, request):
        """
        Log out the user and delete the JWT cookie.

        :param request: HTTP GET request
        :type request: HttpRequest
        :return: Redirects to login page
        :rtype: HttpResponse
        """
        response = redirect('product-list')
        response.delete_cookie('jwt')
        logout(request)
        return response


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject.txt'
    success_message = PASSWORD_RESET_SUCCESS_MESSAGE
    success_url = reverse_lazy('product-list')

ArbiShop/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!--Font awesome icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "style.css" %}"/>

    <title>{% block title %} {% endblock %} </title>
    {% block extra_head %} {% endblock %}
</head>
<body>
  <div class="container p-3 my-3">
    <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-expand-md navbar-light " style="background-color: #f0f5f5">
          <a href="/" class="navbar-brand">Home</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ml-auto position-relative">
                {% if user.is_authenticated %}
                    <a href="{% url 'users:update_profile' %}" class="nav-item nav-link">Profile</a>
                    <a href="{% url 'users:logout' %}" class="nav-item nav-link">Logout</a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="nav-item nav-link">Sign in</a>
                {% endif %}
                 <a href="{% url "cart" %}" class="nav-item nav-link">
                  <i class="fas fa-shopping-cart"></i>
                  <span id="cart-count" class="badge badge-pill badge-danger position-absolute" style="top: -5px; right: -5px;">0</span>
                </a>
                </div>
            </div>
        </nav>
        <!--Any flash messages pop up in any page because this is the base template-->
        {% if messages %}
          <div class="alert alert-dismissible" role="alert">
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
  <script src="{% static 'javascipt/cart.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>
    {% block extra_scripts %}  {% endblock %}
</body>
</html>

ArbiShop/templates/users/home.html
{% extends "users/../base.html" %}
{% block title %} Home Page {% endblock title%}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Welcome To ArbiShop</h1>
        <hr class="my-4">
        <p class="lead">
            {% if user.is_authenticated %}
                <a class="btn btn-primary btn-lg" href="{% url 'logout' %}" role="button">Logout</a>
                <a class="btn btn-primary btn-lg" href="{% url 'update_profile' %}">Edit Profile</a>

            {% else %}
                <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">Sign in</a>
            {% endif %}
        </p>
    </div>

{% endblock content %}

<a href="{% url 'logout' %}">Logout</a>

ArbiShop/templates/users/login.html
{% extends "users/../base.html" %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
      {% if next %}
        <input type="hidden" name="next" value="{{ next }}">
    {% endif %}
    <button type="submit" class="btn btn-primary">Login</button>
      <p>Don't have an account? <a href="{% url 'users:signup' %}">Sign up here</a></p>
      <a href="{% url 'users:password_reset' %}">Forgot Password?</a>  
  </form>
{% endblock %}

ArbiShop/templates/users/password_reset.html
{% extends "users/../base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:signup' %}">Create A New Account</a><br><br>
                                <a href="{% url 'users:login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

ArbiShop/templates/users/password_reset_complete.html
{% extends "users/../base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'users:login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

ArbiShop/templates/users/password_reset_done.html
{% extends "users/../base.html" %}

{% block content %}
<h2>Password Reset Email Sent</h2>
<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
<p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
{% endblock %}

ArbiShop/templates/users/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}

ArbiShop/templates/users/profile.html
{% extends "users/../base.html" %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
    <div class="row my-3 p-3">
        <h1>This is the profile page for {{user.username}}</h1>
    </div>

{% endblock content %}

ArbiShop/templates/users/update_profile.html
{% extends "users/../base.html" %}

{% block content %}
  <h2>Update Profile</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
{% endblock %}

ArbiShop/templates/users/user_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <img src="{{ user.avatar.url }}" alt="{{ user.username }}" class="card-img-top">
                <div class="card-body text-center">
                    <h5 class="card-title">{{ user.first_name }} {{ user.last_name }}</h5>
                    <p class="card-text">{{ user.email }}</p>
                    <p class="card-text">{{ user.bio }}</p>
                    <a href="{% url 'users:update_profile' %}" class="btn btn-primary mb-3">Update Profile</a>
                    <a href="{% url 'seller:dashboard' %}" class="btn btn-primary">Go To Seller Dashboard</a>

                </div>
            </div>
        </div>
        <div class="col-md-8">
            <h4>Order History</h4>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Order ID</th>
                        <th>Date</th>
                        <th>Total</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                     <tr onclick="window.location='{% url 'orders:order_detail' order.id %}'" style="cursor: pointer;">
                        <td>{{ order.id }}</td>
                        <td>{{ order.payment_date|date:"F j, Y, g:i a" }}</td>
                        <td>${{ order.payment_amount }}</td>
                        <td>{{ order.status }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4" class="text-center">No orders placed.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}