ArbiShop/ArbiShop/urls.py
"""
file:urls.py
    This module defines the url patterns for the djangoTimeProject application.
    URL configuration for ArbiShop project.
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('users/', include('users.urls')),
                  path('', include('products.urls')),
                  path('password-reset-complete/',
                       auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
                       name='password_reset_complete'),
                  path('seller/', include('seller.urls')),
                path('chat/', include('chat.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ArbiShop/chat/urls.py
"""
URL routing for the chat application.

This module defines the URL patterns for the chat application, mapping URLs to views that handle
chat room interactions, including creating or retrieving chat rooms and accessing specific chat rooms.
"""

from django.urls import path
import chat.views as chat_views

urlpatterns = [
    path('<int:room_id>/', chat_views.ChatRoomView.as_view(), name='chat_room'),
    path('start/<int:seller_id>/', chat_views.CreateOrGetChatRoomView.as_view(), name='create_or_get_chat_room'),
]

ArbiShop/orders/urls.py
"""
urls.py

Defines URL patterns for the Orders app, mapping views to routes for checkout,
payment processing, and order success.
"""

from django.urls import path
from django.views.generic import TemplateView

from orders.views import CheckoutView, PaymentView, OrderDetailView

app_name = 'orders'
urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('process-payment/', PaymentView.as_view(), name='process_payment'),
    path('order-success/', TemplateView.as_view(template_name='orders/order_success.html'), name='order_success'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order_detail')
]

ArbiShop/products/urls.py
"""
File: urls.py

Description:
    Defines the URL patterns for the Products app, mapping views to their respective paths.
    This includes routes for listing products, viewing product details, managing the cart,
    and proceeding to checkout.
"""
from django.urls import path, include
from products.views import ProductListView, ProductDetailView, CartView, CategoryProductsView, ReviewCreateView

app_name = ''

urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:pk>/add_review/', ReviewCreateView.as_view(), name='add_review'),
    path('category/<int:category_id>/', CategoryProductsView.as_view(), name='category-products'),
    path('cart/', CartView.as_view(), name='cart'),
    path('orders/', include('orders.urls')),
]

ArbiShop/products/models.py
"""
File: products/models.py

Description:
    Defines the database models for the Products app, including the Category and Product models.
    These models represent the categories of products and the individual products available
    in the e-commerce platform.
"""

from django.conf import settings
from django.db import models


class Category(models.Model):
    """
    Represents a category of products in the e-commerce platform.
    Categories help organize products into different sections.
    """
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="images/", blank=True)
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    Represents an individual product in the e-commerce platform.
    Products belong to a category and are associated with a seller.
    """
    id = models.AutoField(primary_key=True)
    name = models.TextField(blank=False, null=False)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='products')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    image = models.ImageField(upload_to='product_images/', blank=True, null=True, max_length=1024)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name


class Config(models.Model):
    """

    Model to store application configuration settings.
    """
    key = models.CharField(max_length=255, unique=True)
    value = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.key}: {self.value}'


class Review(models.Model):
    """
    Model representing a product review submitted by a user.
    - Associates the review with a product and a user.
    - Includes a rating, an optional comment, and a timestamp for when the review was created.
    - Automatically deletes reviews if the associated product is deleted.
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comment = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Returns a string representation of the review, including the user's name,
        the product name, and the rating.
        """
        return f'{self.user.first_name} {self.user.last_name} - {self.product.name} - {self.rating} stars'

ArbiShop/products/forms.py
"""
File: products/forms.py

Description:
    Custom forms for the Category and Product models used in the Django Admin interface.
"""

from django import forms
from products.models import Product, Category, Config, Review


class CategoryForm(forms.ModelForm):
    """
    Form for managing Category model fields in the admin.
    """

    class Meta:
        model = Category
        fields = ['name', 'description', "image", "featured"]


class ConfigForm(forms.ModelForm):
    """
    Form for managing Config model fields in the admin.
    """

    class Meta:
        model = Config
        fields = ["key", "value"]


class ProductForm(forms.ModelForm):
    """
    Form for managing Product model fields in the admin.
    """

    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'stock', 'seller', 'category', 'is_active', 'image']


class ReviewForm(forms.ModelForm):
    """
    Form for users to submit a review, including a rating and comment,
    with Bootstrap styling applied to the fields.
    """

    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'rating': forms.NumberInput(attrs={
                'class': 'form-control',
                'min': 1,
                'max': 5,
                'placeholder': 'Rate between 1 and 5',
            }),
            'comment': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Write your review here...',
                'rows': 4,
            }),
        }


class ReviewAdminForm(forms.ModelForm):
    """
    Form for admin users to manage reviews, allowing for editing the
    product, rating, user, and comment, with custom styling.
    """

    class Meta:
        model = Review
        fields = ['product', 'rating', 'user', 'comment']
        widgets = {
            'product': forms.Select(
                attrs={'class': 'admin-form-control'}
            ),
            'rating': forms.NumberInput(
                attrs={
                    'class': 'admin-form-control',
                    'min': 1,
                    'max': 5,
                }
            ),
            'comment': forms.Textarea(
                attrs={
                    'class': 'admin-form-control',
                    'rows': 4,
                }
            ),
        }

ArbiShop/products/views.py
"""
File: views.py

Description:
    Contains the view classes for the Products app, managing the display and interaction
    with product listings, product details, the shopping cart, and the checkout process.
    The views are implemented using Django's generic class-based views, with some requiring
    user authentication for access.
"""
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, TemplateView, CreateView
from django_filters.views import FilterView

from products.forms import ReviewForm
from products.models import Product, Category, Review
from products.filters import ProductFilter
from products.utils import get_config_value, user_can_review_product


class CartView(TemplateView):
    """
    Displays the shopping cart page where users can view the products
    they have added to their cart.
    """
    template_name = 'products/cart.html'


class ProductListView(ListView):
    """
    Displays a paginated list of all products available in the e-commerce platform.
    """
    model = Product
    template_name = 'products/product_list.html'
    context_object_name = 'products'
    paginate_by = 10
    print(paginate_by)

    def get_queryset(self):
        """
        Create Query for filtering
        :return:
        :rtype:
        """
        queryset = super().get_queryset()
        self.filterset = ProductFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        """
        fetches the data and provide context data to the template
        :param kwargs:
        :type kwargs:
        :return:
        :rtype:
        """
        context = super().get_context_data(**kwargs)
        context['featured_categories'] = Category.objects.filter(featured=True)
        context['categories'] = Category.objects.all()

        return context


class ProductDetailView(DetailView):
    """
    Displays the details of a specific product, including its description, price,
    and other relevant information.
    """
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        context['reviews'] = Review.objects.filter(product=product).order_by('-created_at')
        context['review_form'] = ReviewForm()

        return context


class CategoryProductsView(FilterView, ListView):
    """
    Shows a paginated and filtered list of products in a category.

    Combines FilterView and ListView to display products in a specific category with filtering.
    Also provides additional context for the current category and all available categories.
    """

    model = Product
    template_name = 'products/category_product_listing.html'
    context_object_name = 'products'
    paginate_by = 10
    filterset_class = ProductFilter

    def get_queryset(self):
        """
        Filters products by the selected category and applies the filter set.
        """
        self.category = get_object_or_404(Category, id=self.kwargs['category_id'])
        queryset = super().get_queryset().filter(category=self.category)
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        """
        Adds the current category, filter set, and all categories to the context.
        """
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        context['filterset'] = self.filterset
        context['categories'] = Category.objects.all()
        return context


@method_decorator(login_required, name='dispatch')
@method_decorator(user_can_review_product, name='dispatch')
class ReviewCreateView(CreateView):
    """
    View to handle the creation of a new review by a user.
    - Ensures the user is logged in and eligible to review the product.
    - Associates the review with the current user and product.
    - Redirects to the product detail page upon successful submission.
    """
    model = Review
    form_class = ReviewForm

    def form_valid(self, form):
        """
        Sets the user and product for the review before saving the form.
        Associates the review with the current user and the product specified by 'pk'.
        """
        form.instance.user = self.request.user
        form.instance.product = get_object_or_404(Product, id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        """
        Returns the URL to redirect to after a successful form submission.
        Redirects to the product detail page of the reviewed product.
        """
        return reverse_lazy('product_detail', kwargs={'pk': self.kwargs['pk']})

ArbiShop/templates/products/add_review.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    <h2 class="mb-4">Add a Review for {{ product.name }}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.rating.label_tag }}
            {{ form.rating }}
        </div>
        <div class="form-group">
            {{ form.comment.label_tag }}
            {{ form.comment }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

ArbiShop/templates/products/cart.html
{% extends 'users/../base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Your Cart</h1>
    <div id="cart-items" class="row">
    </div>
    <div id="cart-summary" class="text-right mt-4">
        <h3>Total: <span id="cart-total"></span></h3>
        <a href="{% url 'orders:checkout' %}" class="btn btn-primary">Proceed to Checkout</a>
    </div>
</div>

<script>
    class Cart {
    constructor() {
        this.cart = this.loadCart();
        this.updateCartCount();
        this.renderCartItems();
    }

    loadCart() {
        return localStorage.getItem('cart') ? JSON.parse(localStorage.getItem('cart')) : {};
    }

    saveCart() {
        localStorage.setItem('cart', JSON.stringify(this.cart));
    }

    updateCartCount() {
        let totalItems = Object.values(this.cart).reduce((total, item) => total + item.quantity, 0);
        document.getElementById('cart-count').textContent = totalItems;
    }

    renderCartItems() {
        let cartItemsContainer = document.getElementById('cart-items');
        let cartTotal = 0;
        cartItemsContainer.innerHTML = '';

        if (Object.keys(this.cart).length === 0) {
            cartItemsContainer.innerHTML = `<p class="alert alert-info">Your cart is empty.</p>`;
            document.getElementById('cart-summary').style.display = 'none';
        } else {
            document.getElementById('cart-summary').style.display = 'block';
        }

        for (let productId in this.cart) {
            let product = this.cart[productId];
            cartTotal += product.price * product.quantity;

            let item = document.createElement('div');
            item.classList.add('col-md-4');
            
            item.innerHTML = `
                <div class="card mb-4 shadow-sm">
                    <img src="${product.image}" class="card-img-top" alt="${product.name}">
                    <div class="card-body">
                        <h5 class="card-title">${product.name}</h5>
                        <p class="card-text"><strong>Price:</strong> ${product.price}</p>
                        <p class="card-text"><strong>Quantity:</strong> ${product.quantity}</p>
                        <button class="btn btn-danger remove-item" data-id="${product.id}">Remove</button>
                    </div>
                </div>
            `;
            cartItemsContainer.appendChild(item);
        }

        document.getElementById('cart-total').textContent = cartTotal.toFixed(2);
        this.updateCheckoutButtonState();
        this.initRemoveItemListeners();
    }

    initRemoveItemListeners() {
        const removeButtons = document.querySelectorAll('.remove-item');
        removeButtons.forEach(button => {
            button.addEventListener('click', (event) => {
                const productId = event.target.getAttribute('data-id');
                this.removeItemFromCart(productId);
            });
        });
    }

    removeItemFromCart(productId) {
        delete this.cart[productId];
        this.saveCart();
        this.renderCartItems();
        this.updateCartCount();
    }

    updateCheckoutButtonState() {
        const checkoutButton = document.querySelector('.btn-primary');
        if (Object.keys(this.cart).length === 0) {
            checkoutButton.disabled = true;
        } else {
            checkoutButton.disabled = false;
        }
    }
}

document.addEventListener('DOMContentLoaded', () => {
    const cart = new Cart();
});

</script>
{% endblock %}

ArbiShop/templates/products/category_product_listing.html
{% extends 'users/../base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class=" mt-4">
{% include "category_listing.html" %}
    <div class="row">
        <div class="col-md-3">
            <div class="card mb-4 mt-lg-5">
                <div class="card-header bg-primary text-white">
                    Filters
                </div>
                <div class="card-body">
                    <form method="get">
                        <div class="mb-3">
                            <label for="{{ filterset.form.name.id_for_label }}" class="form-label">{{ filterset.form.name.label }}</label>
                            {{ filterset.form.name|add_class:"form-control" }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ filterset.form.price__gt.id_for_label }}" class="form-label">{{ filterset.form.price__gt.label }}</label>
                            {{ filterset.form.price__gt|add_class:"form-control" }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ filterset.form.price__lt.id_for_label }}" class="form-label">{{ filterset.form.price__lt.label }}</label>
                            {{ filterset.form.price__lt|add_class:"form-control" }}
                        </div>
                        
                        <div class="mt-3">
                            <button type="submit" class="btn btn-primary w-100">Filter</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-12 my-4">
                    <div class="text-center">
                        <h2 class="text-uppercase font-weight-bold text-dark">Products</h2>
                        <div class="underline bg-primary mx-auto my-3" style="width: 50px; height: 4px;"></div>
                    </div>
                </div>

               {% for product in products %}
                <div class="col-md-4 mb-2">
                    <div class="card mb-4 shadow-sm h-100 product-card">
                        <img src="{{ product.image }}" class="card-img-top" alt="{{ product.name }}">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text flex-grow-1 text-truncate">{{ product.description }}</p>
                            <p class="mb-0 p-0 font-weight-bolder"> <strong>Price: </strong></p>
                            <p class=""> <strong>PKR: </strong> {{ product.price }}</p>
                            <a href="{% url 'product-detail' product.pk %}" class="btn btn-primary mt-auto">View Details</a>
                        </div>
                    </div>
                </div>
                {% empty %}
                <p class="text-center">No products available.</p>
                {% endfor %}
            </div>
            {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="First">
                            <span aria-hidden="true">&laquo;&laquo;</span>
                            <span class="sr-only">First</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}

                    {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                            <span aria-hidden="true">&raquo;&raquo;</span>
                            <span class="sr-only">Last</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

<style>
    .product-card {
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }

    .product-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    }

    .product-card img {
        transition: transform 0.3s ease;
    }

    .product-card:hover img {
        transform: scale(1.05);
    }

    .product-card .btn-primary {
        transition: background-color 0.3s ease, border-color 0.3s ease;
    }

    .product-card:hover .btn-primary {
        background-color: #0056b3;
        border-color: #004085;
    }
</style>

ArbiShop/templates/products/checkout.html
{% extends 'users/../base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Checkout</h1>
    <div class="row">
        <div class="col-md-6">
            <h3>Your Cart</h3>
            <div id="cart-items">
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-6">
            <h3>Order Summary</h3>
            <p><strong>Total Items:</strong> <span id="total-items"></span></p>
            <p><strong>Total Price:</strong> $<span id="total-price"></span></p>
            <a id="checkout-btn" href="{% url "orders:process_payment" %}" class="btn btn-primary btn-lg">Proceed to Payment</a>
        </div>
    </div>
</div>

<script>
    class Checkout {
        constructor() {
            this.cart = this.loadCart();
            this.renderCartItems();
            this.calculateTotal();
        }

        loadCart() {
            return localStorage.getItem('cart') ? JSON.parse(localStorage.getItem('cart')) : {};
        }

        renderCartItems() {
            let cartItemsContainer = document.getElementById('cart-items');
            cartItemsContainer.innerHTML = '';

            for (let productId in this.cart) {
                let product = this.cart[productId];

                let item = document.createElement('div');
                item.classList.add('card', 'mb-3');
                item.innerHTML = `
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img src="${product.image}" class="card-img" alt="${product.name}">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">${product.name}</h5>
                                <p class="card-text"><strong>Price:</strong> $${product.price}</p>
                                <p class="card-text"><strong>Quantity:</strong> ${product.quantity}</p>
                            </div>
                        </div>
                    </div>
                `;
                cartItemsContainer.appendChild(item);
            }
        }

        calculateTotal() {
            let totalItems = 0;
            let totalPrice = 0;

            for (let productId in this.cart) {
                let product = this.cart[productId];
                totalItems += product.quantity;
                totalPrice += product.price * product.quantity;
            }

            document.getElementById('total-items').textContent = totalItems;
            document.getElementById('total-price').textContent = totalPrice.toFixed(2);
        }
    }

    document.addEventListener('DOMContentLoaded', () => {
        const checkout = new Checkout();
    });
</script>
{% endblock %}

ArbiShop/templates/products/product_detail.html
{% extends 'users/../base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ product.image }}" class="img-fluid" alt="{{ product.name }}">
        </div>
        <div class="col-md-6">
            <h1>{{ product.name }}</h1>
            <p class="text-muted">{{ product.category.name }}</p>
            {% if user.is_authenticated %}
                <a href="{% url 'create_or_get_chat_room' product.seller.id %}">Chat with Seller</a>
            {% else %}
                <a href="{% url 'login' %}?next={% url 'create_or_get_chat_room' product.id %}">Login to Chat with Seller</a>
            {% endif %}

            
            <p>{{ product.description }}</p>
            <p class="mb-0 p-0 font-weight-bolder"><strong>Price: </strong></p>
            <p><strong>PKR: </strong> {{ product.price }}</p>
            <p><strong>Stock:</strong> {{ product.stock }}</p>
            <button id="add-to-cart-btn"
                class="btn btn-success btn-lg mt-3"
                data-product-id="{{ product.id }}"
                data-product-name="{{ product.name }}"
                data-product-price="{{ product.price }}"
                data-product-image-url="{{ product.image }}">
                Add to Cart
            </button>
        </div>
    </div>

    <!-- Reviews Section -->
    <div class="mt-5">
        <h3>Customer Reviews</h3>
        {% if reviews %}
            <ul class="list-group">
                {% for review in reviews %}
                    <li class="list-group-item">
                        <div class="d-flex justify-content-between">
                            <div>
                                <div class="">
                                    <strong>{{ review.user.first_name }}</strong>
                                    <p >
                                        {{ review.rating }}
                                            <span class="text-warning">★</span>
                                    </p>
                                </div>
                                <p>{{ review.comment }}</p>
                            </div>
                            <small class="text-muted">{{ review.created_at|date:"F j, Y, g:i a" }}</small>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No reviews yet. Be the first to write a review!</p>
        {% endif %}
    </div>

    <!-- Review Form -->
    <div class="mt-5">
        <h4>Write a Review</h4>
        <form method="post" action="{% url 'add_review' product.id %}">
            {% csrf_token %}
            <div class="form-group">
                {{ review_form.rating.label_tag }}
                {{ review_form.rating }}
            </div>
            <div class="form-group">
                {{ review_form.comment.label_tag }}
                {{ review_form.comment }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>
{% endblock %}

ArbiShop/templates/products/slider.html
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-indicators">
    {% for category in featured_categories %}
      <button type="button" data-bs-target="#carouselExampleFade" data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}" aria-current="{% if forloop.first %}true{% endif %}" aria-label="Slide {{ forloop.counter }}"></button>
    {% endfor %}
  </div>
  <div class="carousel-inner">
    {% for category in featured_categories %}
    <div class="carousel-item {% if forloop.first %}active{% endif %}">
      <a href="{% url 'category-products' category.id %}">
        <img src="{{ category.image.url }}" class="d-block w-100 carousel-image" alt="{{ category.name }}">
        <div class="carousel-caption d-md-block">
          <h5>{{ category.name }}</h5>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<style>
.carousel-image {
    height: 500px;
    object-fit: cover; 
}

.carousel-caption {
    background-color: rgba(0, 0, 0, 0.5); 
    padding: 15px;
    border-radius: 5px;
}


.carousel-control-prev:hover,
.carousel-control-next:hover {
    background-color: rgba(0, 0, 0, 0.2);
}
</style>